---
title: "Central Limit Theorem"
output: html_notebook
---
Example CLT applied to the Uniform Continuous Distribution(min = 2, max = 6)
```{r}
library(ggplot2)
#create empty vector to hold sample means
sample30 <- c()
#take 1,000 random samples of size n=30
n = 10000
for (i in 1:n){
sample30[i] = mean(runif(1000, min=0, max = 1))
}
df <- data.frame(value = sample30)
ggplot(data = df,aes(value))+geom_histogram(bins=60)
```
```{r}
qqnorm(df$value, main = "Normal Quantile-Quantile Plot")
qqline(df$value, col = "2")
```
 
Example CLT applied to the Exponential Distribution (rate = 2)
```{r}
library(ggplot2)
#create empty vector to hold sample means
sample30 <- c()
data <- rexp(n=1000, rate = 2)
#take 1,000 random samples of size n=30
n = 10000
for (i in 1:n){
sample30[i] = mean(rexp(n=1000, rate = 2))
}
df <- data.frame(value = sample30)
ggplot(data = df,aes(value))+geom_histogram(bins=60)
```


```{r}
qqnorm(df$value, main = "Normal Quantile-Quantile Plot")
qqline(df$value, col = "2")
```
